<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceCategory;
use App\Models\ServiceSubCategory;
use App\Models\Service;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    public function run()
    {
        // 1. Create Main Categories
        $categories = [
            [
                'name' => 'Laboratory',
                'type' => 'laboratory',
                'description' => 'Medical laboratory tests and analysis',
                'status' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Imaging',
                'type' => 'imaging',
                'description' => 'Radiology and diagnostic imaging services',
                'status' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Procedures',
                'type' => 'procedure',
                'description' => 'Medical procedures and minor surgeries',
                'status' => true,
                'sort_order' => 3,
            ],
        ];

        foreach ($categories as $catData) {
            $category = ServiceCategory::updateOrCreate(
                ['slug' => Str::slug($catData['name'])],
                $catData
            );

            if ($catData['type'] === 'laboratory') {
                $this->seedLaboratoryServices($category);
            }
        }
    }

    private function seedLaboratoryServices($category)
    {
        $data = [
            'HEMATOLOGY' => [
                ['name' => 'Hemoglobin(Hb%)', 'price' => 200, 'specimen' => 'EDTA Tube'],
                ['name' => 'Complete Blood Count (CBC) with ESR', 'price' => 250, 'specimen' => 'EDTA Tube'],
                ['name' => 'Erythrocyte Sedimentation Rate (ESR)', 'price' => 100, 'specimen' => 'EDTA Tube'],
                ['name' => 'Periferal Blood Film / PBF', 'price' => 200, 'specimen' => 'EDTA Tube'],
                ['name' => 'Total Circulating Eosinophil Count (TCE)', 'price' => 200, 'specimen' => 'EDTA Tube'],
                ['name' => 'Reticulocyte Count (R/C count)', 'price' => 250, 'specimen' => 'EDTA Tube'],
                ['name' => 'LE (Lupus Erythematosus) Cell', 'price' => 250, 'specimen' => 'EDTA Tube'],
                ['name' => 'Platelete Count', 'price' => 200, 'specimen' => 'EDTA Tube'],
                ['name' => 'Blood Group & RH Factor', 'price' => 100, 'specimen' => 'EDTA Tube'],
                ['name' => 'Hematocrit/HCT/PCV', 'price' => 200, 'specimen' => 'EDTA Tube'],
                ['name' => 'Micro Filaria', 'price' => 500, 'specimen' => 'EDTA Tube'],
                ['name' => 'Hb Electrophoresis (Capillary)', 'price' => 750, 'specimen' => 'EDTA Tube'],
                ['name' => 'Hb Electrophoresis (HPLC)', 'price' => 650, 'specimen' => 'EDTA Tube'],
            ],
            'COAGULATION' => [
                ['name' => 'Prothrombin Time (PT)', 'price' => 300, 'specimen' => 'PT Tube'],
                ['name' => 'Activated Partial Thromboplastin Time (APTT)', 'price' => 350, 'specimen' => 'PT Tube'],
                ['name' => 'D-Dimer', 'price' => 700, 'specimen' => 'PT Tube'],
                ['name' => 'FACTOR V', 'price' => 4500, 'specimen' => 'PT Tube'],
                ['name' => 'FACTOR VII', 'price' => 3000, 'specimen' => 'PT Tube'],
                ['name' => 'FACTOR VIII', 'price' => 750, 'specimen' => 'PT Tube'],
                ['name' => 'FACTOR IX', 'price' => 750, 'specimen' => 'PT Tube'],
                ['name' => 'Protein C', 'price' => 3000, 'specimen' => 'PT Tube'],
                ['name' => 'Protein S', 'price' => 3000, 'specimen' => 'PT Tube'],
                ['name' => 'Anti Thrombin III', 'price' => 4000, 'specimen' => 'PT Tube'],
                ['name' => 'Plasma Fibrinogen', 'price' => 650, 'specimen' => 'PT Tube'],
                ['name' => 'FDP-Fibrin Degradation Product', 'price' => 800, 'specimen' => 'PT Tube'],
                ['name' => 'Lupus Anticoagulant (LA)', 'price' => 2000, 'specimen' => 'PT Tube'],
                ['name' => 'Lupus Anticoagulant Panel (aPTT-LA-dRVVT)', 'price' => 4000, 'specimen' => 'PT Tube'],
                ['name' => 'Coombs Test - Direct/Indirect', 'price' => 500, 'specimen' => 'Serum+EDTA'],
            ],
            'DIABETES (ENDOCRINOLOGY & METABOLISM)' => [
                ['name' => 'FBS (Fasting Blood Sugar)', 'price' => 100, 'specimen' => 'Gray Tube'],
                ['name' => '2 Hrs After Breakfast', 'price' => 100, 'specimen' => 'Gray Tube'],
                ['name' => 'RBS (Random Blood Sugar)', 'price' => 100, 'specimen' => 'Gray Tube'],
                ['name' => '1 Hr 75 gm Glucose', 'price' => 100, 'specimen' => 'Gray Tube'],
                ['name' => '2 Hrs 75 gm Glucose', 'price' => 100, 'specimen' => 'Gray Tube'],
                ['name' => 'OGTT-2 Samples', 'price' => 200, 'specimen' => 'Gray Tube'],
                ['name' => 'OGTT-3 Samples', 'price' => 300, 'specimen' => 'Gray Tube'],
                ['name' => 'PPBS (Post Prandial Blood Sugar)', 'price' => 100, 'specimen' => 'Gray Tube'],
                ['name' => 'Urine Microalbumin', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Urine ACR', 'price' => 500, 'specimen' => 'Urine'],
                ['name' => 'HbA1c', 'price' => 500, 'specimen' => 'EDTA Tube'],
                ['name' => 'Insulin', 'price' => 600, 'specimen' => 'F. Serum'],
                ['name' => 'HOMA IR', 'price' => 1000, 'specimen' => 'F. Serum+Gray Tube'],
                ['name' => 'Aldosterone', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'C-Peptide', 'price' => 1500, 'specimen' => 'Serum'],
            ],
            'RENAL FUNCTIONS' => [
                ['name' => 'Renal Function Tests-KFT/RFT (Creat.,Urea,BUN,eG)', 'price' => 550, 'specimen' => 'Serum'],
                ['name' => 'S. Creatinine', 'price' => 150, 'specimen' => 'Serum'],
                ['name' => 'Urine Creatinine', 'price' => 150, 'specimen' => 'Serum'],
                ['name' => 'Blood Urea Nitrogen (BUN)', 'price' => 150, 'specimen' => 'Serum'],
                ['name' => 'eGFR', 'price' => 350, 'specimen' => 'Serum'],
                ['name' => 'CCR-24 Hrs Urine', 'price' => 400, 'specimen' => '24 Hrs Urine'],
                ['name' => 'Anti GBM-IgG', 'price' => 4000, 'specimen' => 'Serum'],
                ['name' => 'Cystatin C', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Citric Acid (Blood/Semen)', 'price' => 1400, 'specimen' => 'Serum/Semen'],
            ],
            'HEART/CARDIAC DISEASE' => [
                ['name' => 'Lipid Profile', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Total Cholesterol', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Triglycerides(TG)', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'HDL- Direct', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'LDL - Direct', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Troponin I', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'NT Pro BNP', 'price' => 1200, 'specimen' => 'Serum'],
                ['name' => 'BNP', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'CK-MB', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'CK/CPK', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'LDH-Lactate dehydrogenase', 'price' => 350, 'specimen' => 'Serum'],
                ['name' => 'Myoglobin', 'price' => 650, 'specimen' => 'Serum'],
            ],
            'ANEMIA PROFILE' => [
                ['name' => 'Iron Profile', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Serum Iron', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Total Iron Binding Capacity (TIBC)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Serum Ferritin', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Serum Folic Acid/Folate', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Glucose-6-Phosphate Dehydrogenase/G6PD', 'price' => 3000, 'specimen' => 'EDTA'],
                ['name' => 'Ceruloplasmin', 'price' => 1200, 'specimen' => 'Serum'],
            ],
            'ELECTROLYTES' => [
                ['name' => 'Electrolytes (Serum)', 'price' => 300, 'specimen' => 'Lithium Heparin'],
                ['name' => 'Electrolytes (Spot Urine)', 'price' => 500, 'specimen' => 'Spot Urine'],
                ['name' => 'Electrolytes (24 Hrs. Urine)', 'price' => 500, 'specimen' => '24 Hrs Urine'],
                ['name' => 'Magnesium (Serum)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Magnesium (24 Hrs. Urine)', 'price' => 600, 'specimen' => '24 Hrs Urine'],
                ['name' => 'Lithium', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'Serum Zinc', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'Serum Copper', 'price' => 900, 'specimen' => 'Serum'],
                ['name' => 'Plasma Osmolality', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'Urinary Osmolality', 'price' => 600, 'specimen' => 'Urine'],
                ['name' => '24 Hrs Urine Copper', 'price' => 3000, 'specimen' => '24 Hrs Urine'],
            ],
            'LIVER DISEASE' => [
                ['name' => 'Liver Function Test /LFT(T.Bili,AST,ALT.ALP)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'SGPT (Alanine Transaminase)/ALT', 'price' => 150, 'specimen' => 'Serum'],
                ['name' => 'SGOT (Aspartate aminotransferase)/AST', 'price' => 150, 'specimen' => 'Serum'],
                ['name' => 'Alkaline Phosphatase (ALP)', 'price' => 150, 'specimen' => 'Serum'],
                ['name' => 'GGT/Gama-GT', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'Bilirubin T/D/I', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Bilirubin - Total', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Bilirubin -Direct', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Bilirubin -Indirect', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Protein Profile (TP, ALB,GLB,AGR)', 'price' => 550, 'specimen' => 'Serum'],
                ['name' => 'Total Protein', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Serum Albumin', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Serum Globulin', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'Serum Amylase', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Urine Amylase', 'price' => 400, 'specimen' => 'Spot/24 Hrs. Urine'],
                ['name' => 'Serum Lipase', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Urine Lipase', 'price' => 400, 'specimen' => 'Spot/24 Hrs. Urine'],
                ['name' => 'Anti Parietal Cell', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Acid Phosphatase (Prostatic)', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Acid Phosphatase (Total)', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'Bile acids', 'price' => 2500, 'specimen' => 'Serum'],
                ['name' => 'Aldolase', 'price' => 1000, 'specimen' => 'Serum'],
            ],
            'THYROID DISORDERS' => [
                ['name' => 'Total Triiodothyronine (T3)', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'Total Thyroxine (T4)', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'Thyroid Stimulating Hormone (TSH)', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'Free Triiodothyronine (FT3)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'Free Thyroxine (FT4)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'T3, T4, TSH', 'price' => 750, 'specimen' => 'Serum'],
                ['name' => 'Anti Thyroid Antibody', 'price' => 1000, 'specimen' => 'Serum'],
                ['name' => 'Anti Thyroglobulin Antibody (ATG)/Anti TG', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Anti Microsomal Antibody (AMA)/TPO', 'price' => 550, 'specimen' => 'Serum'],
                ['name' => 'Thyroglobulin', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'S. Calcitonin/Thyrocalcitonin', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Anti TSH Receptor Antibody (TRAB)', 'price' => 1500, 'specimen' => 'Serum'],
            ],
            'REPRODUCTIVE TESTS' => [
                ['name' => 'Beta HCG', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Luteinizing Hormone (LH)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Follicle Stimulating Hormone (FSH)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'LH-FSH Ratio', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Prolactin (PRL)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Estradiol/Oestrogen (E2)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Progesterone', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => '17 OH Progesterone', 'price' => 1800, 'specimen' => 'Serum'],
                ['name' => 'Testosterone', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Free Testosterone', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Dihydrotestosterone', 'price' => 2500, 'specimen' => 'Serum'],
                ['name' => 'Testosterone:Dihydrotestosterone Ratio', 'price' => 2500, 'specimen' => 'Serum'],
                ['name' => 'Anti Mullerian Hormone (AMH)', 'price' => 1400, 'specimen' => 'Serum'],
                ['name' => 'RH Antibody Titre/Anti D Titre', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'Semen for Fructose', 'price' => 1000, 'specimen' => 'Semen'],
                ['name' => 'Semen Analysis', 'price' => 500, 'specimen' => 'Semen'],
                ['name' => 'Sex Hormone Binding Globulin (SHBG)', 'price' => 1000, 'specimen' => 'Serum'],
                ['name' => 'Anti Sperm Antibody (ASAB)', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Inhibin A', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Inhibin B', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Free Beta hCG', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'Pregnancy Associated Plasma Protein A (PAPP-A)', 'price' => 2500, 'specimen' => 'Serum'],
            ],
            'CANCER/TUMOR MARKERS' => [
                ['name' => 'PSA (Prostate Specific Antigen) Total', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Free PSA', 'price' => 700, 'specimen' => 'Serum'],
                ['name' => 'Alpha Fetoprotein (AFP)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Carcinoembryonic antigen (CEA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'CA-125', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'CA-19.9', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'CA-15.3', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Beta 2 Microglubulin', 'price' => 700, 'specimen' => 'Serum'],
                ['name' => '5-Dihydrotestosterone/5- DHT', 'price' => 5000, 'specimen' => 'Serum/Urine'],
                ['name' => 'Bence Jones Protein, Urine', 'price' => 500, 'specimen' => 'Urine'],
                ['name' => 'Protein Electrophoresis', 'price' => 950, 'specimen' => 'Serum'],
                ['name' => 'Immuno Electrophoresis', 'price' => 5000, 'specimen' => 'Serum'],
            ],
            'ENDOCRINE & METABOLIC DISORDER' => [
                ['name' => 'Intact Parathyroid Hormone (PTH)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Serum Cortisol', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Cortisol Morning (7.00-9.00 am)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Cortisol Evening (3.00-5.00 pm)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Basal Cortisol', 'price' => 400, 'specimen' => 'Fasting Serum'],
                ['name' => '24 Hrs Urine Cortisol', 'price' => 450, 'specimen' => '24 Hrs Urine'],
                ['name' => 'Short Synacthen Test', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'Human Growth Hormone (HGH)', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'DHEA - Sulphate (DHEAS)/DHEA-SO4', 'price' => 750, 'specimen' => 'Serum'],
                ['name' => 'Androstenedione (A4)', 'price' => 3500, 'specimen' => 'Serum'],
                ['name' => 'Adrenocorticotropic Hormone (ACTH)', 'price' => 650, 'specimen' => 'EDTA'],
            ],
            'INFECTIOUS DISEASES (VIRAL MARKER)' => [
                ['name' => 'HBsAg (ICT)', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'HBsAg (ELISA)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'HBsAg (CLIA)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Anti HBs Total/Titre (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'HBeAg (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Anti HBe/ HBeAb (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Anti HBc Total (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Anti HBc-IgM (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Anti HCV (ICT)', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'Anti HCV Total (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Anti HCV Total (CLIA)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Anti HAV IgM (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Anti HEV IgM (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'HIV 1+2 (ICT)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'HIV 1+2 (ELISA)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'HIV 1+2 (CLIA)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'ToRCH Panel Antibody', 'price' => 3800, 'specimen' => 'Serum'],
                ['name' => 'ToRCH Panel (IgG)', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'ToRCH Panel (IgM)', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Toxo - IgG (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Toxo - IgM (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Rubella - IgG (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Rubella- IgM (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Cytomegalo Virus (CMV) -IgG (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Cytomegalo Virus (CMV) - IgM (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Herpes Simplex Virus (HSV) 1 IgG (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Herpes Simplex Virus (HSV) 1 IgM (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Herpes Simplex Virus (HSV) 2-IgG (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Herpes Simplex Virus (HSV) 2-IgM (ELISA)', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Herpes Simplex Virus (HSV) 1+2-IgG (ELISA)', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'Herpes Simplex Virus (HSV) 1+2-IgM (ELISA)', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'Procalcitonin (PCT)', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'H. Pylori IgG (ELISA)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Anti TB IgM+IgG+IGA ( ELISA)', 'price' => 2100, 'specimen' => 'Serum'],
                ['name' => 'Anti TB IgM/IgG/IGA ( ELISA)', 'price' => 700, 'specimen' => 'Serum'],
                ['name' => 'Anti Chlamydial Antibody (IgG+IgM)', 'price' => 1800, 'specimen' => 'Serum'],
                ['name' => 'Anti Chlamydial Antibody (ICT)', 'price' => 1000, 'specimen' => 'Serum'],
                ['name' => 'Tacrolimus', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Interleukin-6 (IL-6)', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Leptospiral Antibody', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'Leptospiral Antibody (IgG+IgM) (ELISA)', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Echinococcus Antibody (ELISA)', 'price' => 1800, 'specimen' => 'Serum'],
                ['name' => 'Quantiferon TB Gold', 'price' => 4000, 'specimen' => 'Lithium Heparin'],
                ['name' => 'Quantiferon TB Gold Plus', 'price' => 5500, 'specimen' => 'Lithium Heparin'],
            ],
            'ARTHRITIS DISEASE' => [
                ['name' => 'ASO titre (Anti Streptolysin - "O")', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'Rheumatoid Factor (RF) / (RA)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'C-Reactive Protein (CRP)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'Serum Calcium', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Urine Calcium', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Serum Phosphorous/Inorganic PO4', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Urine Phosphorous/Inorganic PO4', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Serum Uric Acid', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Urine Uric Acid', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Anti Cyclic Citrullinated Peptide Antibody (ACCP)', 'price' => 700, 'specimen' => 'Serum'],
                ['name' => 'Rose Waaler Test', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'ENA Profile (Quantitative)', 'price' => 5000, 'specimen' => 'Serum'],
            ],
            'AUTO-IMMUNE DYSFUNCTIONS' => [
                ['name' => 'Total IgE', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Specific IgE (60 Parameter)', 'price' => 5000, 'specimen' => 'Serum'],
                ['name' => 'Allergy Panel (Food)', 'price' => 5000, 'specimen' => 'Serum'],
                ['name' => 'Allergy Panel (Inhalation)', 'price' => 5000, 'specimen' => 'Serum'],
                ['name' => 'Immunoglobulin A (IgA)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Immunoglobulin G (IgG)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Immunoglobulin M (IgM)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Anti Nuclear Antibodies (ANA) / ANF', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'ANA Hep2', 'price' => 1000, 'specimen' => 'Serum'],
                ['name' => 'Anti - ds DNA', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Complement 3 (C3)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Complement 4 (C4)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'Anti Phospholipid Ab', 'price' => 1200, 'specimen' => 'Serum'],
                ['name' => 'Anti Phospholipid Antiobdy (IgG & IgM)', 'price' => 1700, 'specimen' => 'Serum'],
                ['name' => 'Anti Cardiolipin Antibody', 'price' => 1000, 'specimen' => 'Serum'],
                ['name' => 'Anti Cardiolipin Antibody (IgM & IgG)', 'price' => 1700, 'specimen' => 'Serum'],
                ['name' => 'Beta 2 Glycoprotein 1 Screening', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Beta 2 Glycoprotein 1 (IgG/IgM/IgA)', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Anti Saccharomyces Cerevisiae Antibody-ASCA', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'Liver Kidney Microsomes (LKM)', 'price' => 1800, 'specimen' => 'Serum'],
                ['name' => 'Mitochondrial Antibody (AMA-M2)', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'ACE -Angiotensin Converting Enzyme', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Acetylcholine Receptor Antibody (ACHR)', 'price' => 6000, 'specimen' => 'Serum'],
                ['name' => 'IGF-1/Somatomedin-C', 'price' => 3000, 'specimen' => 'Serum'],
                ['name' => 'Kappa Free Light Chain (KFLC)', 'price' => 4000, 'specimen' => 'Serum'],
                ['name' => 'Lamda Free Light Chain (LFLC)', 'price' => 4000, 'specimen' => 'Serum'],
                ['name' => 'Histone Antibodies', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'Anti RNP Ab', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'Jo-1 Antibody', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'C1 Esterase Inhibitor', 'price' => 3500, 'specimen' => 'Serum'],
                ['name' => 'Sm (SMITH) Antibody IgG', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'Smooth Muscle Antibody (ASMA)', 'price' => 2500, 'specimen' => 'Serum'],
                ['name' => 'Tissue Transglutaminase(TTG) - IgA', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Anti Centromere Ab', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Anti Ro / SS-A', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'SS-B/La Antibody', 'price' => 1750, 'specimen' => 'Serum'],
                ['name' => 'Pr3-ANCA (C-ANCA)', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'MPO-ANCA (P-ANCA)', 'price' => 600, 'specimen' => 'Serum'],
                ['name' => 'Anti SCL-70 Antibody', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Anti MDA-5 Antibody', 'price' => 2000, 'specimen' => 'Serum'],
                ['name' => 'Wilson\'s Disease Panel', 'price' => 4500, 'specimen' => 'Serum'],
                ['name' => 'APS (Anti Phospholopid Syndrome) Panel', 'price' => 6000, 'specimen' => 'Serum+PT Tube'],
            ],
            'CLINICAL PATHOLOGY (URINE+STOOL)' => [
                ['name' => 'Urine RME/Urinogram (Auto)', 'price' => 150, 'specimen' => 'Urine'],
                ['name' => 'Urobilinogen Urine', 'price' => 150, 'specimen' => 'Urine'],
                ['name' => 'Phase Contrast/Urine for Dysmorphic RBC', 'price' => 800, 'specimen' => 'Urine'],
                ['name' => 'Urine for Ketone bodies (Acetone)', 'price' => 120, 'specimen' => 'Urine'],
                ['name' => 'Urine for PH', 'price' => 150, 'specimen' => 'Urine'],
                ['name' => 'Urine Specific Gravity', 'price' => 150, 'specimen' => 'Urine'],
                ['name' => 'Urine Albumin / Heat Coagulant test of Urine', 'price' => 100, 'specimen' => 'Urine'],
                ['name' => 'Urine for Sugar / CUS', 'price' => 100, 'specimen' => 'Urine'],
                ['name' => 'Spot Urine Albumin', 'price' => 100, 'specimen' => 'Urine'],
                ['name' => '24 hrs Urine T. Protein (UTP)', 'price' => 250, 'specimen' => '24 Hrs Urine'],
                ['name' => 'Urine Protein Creatinine Ratio (PCR)-Spot Urine', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Stool OBT (Fecal Occult Blood)', 'price' => 200, 'specimen' => 'Stool'],
                ['name' => 'Stool R/M/E', 'price' => 150, 'specimen' => 'Stool'],
                ['name' => 'Stool for Reducing Substance/Stool R/S', 'price' => 100, 'specimen' => 'Stool'],
                ['name' => 'Fecal Calprotectin Stool', 'price' => 2000, 'specimen' => 'Stool'],
            ],
            'MICROBIOLOGY TESTS' => [
                ['name' => 'Urine for AFB Stain', 'price' => 200, 'specimen' => 'Urine'],
                ['name' => 'Urine for Gram Stain', 'price' => 200, 'specimen' => 'Urine'],
                ['name' => 'Urine for C/S', 'price' => 200, 'specimen' => 'Urine'],
                ['name' => 'Blood for C/S (FAN Method)', 'price' => 600, 'specimen' => 'FAN Bottle'],
                ['name' => 'Stool for C/S', 'price' => 250, 'specimen' => 'Stool'],
                ['name' => 'Sputum for AFB Stain', 'price' => 200, 'specimen' => 'Sputum'],
                ['name' => 'Sputum for Gram Stain/RE', 'price' => 200, 'specimen' => 'Sputum'],
                ['name' => 'Sputum for Eosinophil Count', 'price' => 200, 'specimen' => 'Sputum'],
                ['name' => 'Sputum for C/S', 'price' => 250, 'specimen' => 'Sputum'],
                ['name' => 'Aspirate Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Aspirate Fluid'],
                ['name' => 'Aspirate Fluid for CS', 'price' => 250, 'specimen' => 'Aspirate Fluid'],
                ['name' => 'Ascitic Fluid for AFB Stain', 'price' => 200, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Ascitic Fluid for Gram Stain', 'price' => 200, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Ascitic Fluid for C/S', 'price' => 250, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'High Vaginal Swab (HVS) for Gram Stain/RE', 'price' => 200, 'specimen' => 'HVS'],
                ['name' => 'High Vaginal Swab (HVS) for C/S', 'price' => 250, 'specimen' => 'HVS'],
                ['name' => 'Pleural Fluid for AFB Stain', 'price' => 200, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pleural Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pleural Fluid for C/S', 'price' => 250, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pericardial Fluid for AFB Stain', 'price' => 200, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Pericardial Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Pericardial Fluid for CS', 'price' => 250, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Peritoneal Fluid for AFB Stain', 'price' => 200, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Peritoneal Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Peritoneal Fluid for CS', 'price' => 250, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Urethral Discharge for AFB Stain', 'price' => 200, 'specimen' => 'Urethral Discharge'],
                ['name' => 'Urethral Discharge for Gram Stain/RE', 'price' => 200, 'specimen' => 'Urethral Discharge'],
                ['name' => 'Urethral Discharge for CS', 'price' => 250, 'specimen' => 'Urethral Discharge'],
                ['name' => 'Nail Clipping for Fungus (ME)', 'price' => 200, 'specimen' => 'Nail Clipping'],
                ['name' => 'Nail Clipping for C/S', 'price' => 250, 'specimen' => 'Nail Clipping'],
                ['name' => 'Prostatic Smear (P/S) for Gram Stain/RE', 'price' => 200, 'specimen' => 'Prostatic Smear'],
                ['name' => 'Prostatic Smear (P/S) for C/S', 'price' => 250, 'specimen' => 'Prostatic Smear'],
                ['name' => 'PUS for AFB Stain', 'price' => 200, 'specimen' => 'PUS'],
                ['name' => 'PUS for Gram stain/RE', 'price' => 200, 'specimen' => 'PUS'],
                ['name' => 'PUS for C/S', 'price' => 250, 'specimen' => 'PUS'],
                ['name' => 'CSF for AFB Stain', 'price' => 200, 'specimen' => 'CSF'],
                ['name' => 'CSF for Gram Stain', 'price' => 200, 'specimen' => 'CSF'],
                ['name' => 'CSF for CS', 'price' => 250, 'specimen' => 'CSF'],
                ['name' => 'Conjunctival Swab for Gram Stain', 'price' => 200, 'specimen' => 'Conjunctival Swab'],
                ['name' => 'Conjunctival Swab for C/S', 'price' => 250, 'specimen' => 'Conjunctival Swab'],
                ['name' => 'Cervical Swab for Gram Stain/RE', 'price' => 200, 'specimen' => 'Cervical Swab'],
                ['name' => 'Cervical Swab for CS', 'price' => 250, 'specimen' => 'Cervical Swab'],
                ['name' => 'Cystic Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Cystic Fluid for CS', 'price' => 250, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Catheter Tip for CS', 'price' => 250, 'specimen' => 'Catheter Tip'],
                ['name' => 'Joint Fluid for AFB Stain', 'price' => 200, 'specimen' => 'Joint Fluid'],
                ['name' => 'Joint Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Joint Fluid'],
                ['name' => 'Joint Fluid for CS', 'price' => 250, 'specimen' => 'Joint Fluid'],
                ['name' => 'Skin Scraping for Fungus (ME)', 'price' => 200, 'specimen' => 'Skin'],
                ['name' => 'Skin Scraping for Fungus Culture (Skin C/S)', 'price' => 500, 'specimen' => 'Skin'],
                ['name' => 'Synovial Fluid for AFB Stain', 'price' => 200, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Synovial Fluid for Gram Stain/RE', 'price' => 200, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Synovial Fluid for C/S', 'price' => 250, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Throat Swab for Gram Stain/RE', 'price' => 200, 'specimen' => 'Throat Swab'],
                ['name' => 'Throat Swab for C/S', 'price' => 250, 'specimen' => 'Throat Swab'],
                ['name' => 'Tracheal Aspirate for Gram Stain/RE', 'price' => 200, 'specimen' => 'Tracheal Aspirate'],
                ['name' => 'Tracheal Aspirate for C/S', 'price' => 250, 'specimen' => 'Tracheal Aspirate'],
                ['name' => 'Umbilical Swab for C/S', 'price' => 250, 'specimen' => 'Umbilical Swab'],
                ['name' => 'Wound Swab for AFB Stain', 'price' => 200, 'specimen' => 'Wound Swab'],
                ['name' => 'Wound Swab for Gram Stain', 'price' => 200, 'specimen' => 'Wound Swab'],
                ['name' => 'Wound Swab for C/S', 'price' => 250, 'specimen' => 'Wound Swab'],
                ['name' => 'Ear Swab for Gram Stain/RE', 'price' => 200, 'specimen' => 'Ear Swab'],
                ['name' => 'Ear Swab for C/S', 'price' => 250, 'specimen' => 'Ear Swab'],
                ['name' => 'Nasal Swab for CS', 'price' => 250, 'specimen' => 'Nasal Swab'],
                ['name' => 'Nipple Discharge for CS', 'price' => 250, 'specimen' => 'Nipple Discharge'],
                ['name' => 'Hair Pluck for Fungus (ME)', 'price' => 200, 'specimen' => 'Hair Pluck'],
                ['name' => 'Hair Pluck for C/S', 'price' => 500, 'specimen' => 'Hair Pluck'],
            ],
            'SEROLOGY' => [
                ['name' => 'Widal Test', 'price' => 200, 'specimen' => 'Serum'],
                ['name' => 'Febrile Antigen/ Triple Antigen', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Weil-Felix Test', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'VDRL (Qualitative)', 'price' => 300, 'specimen' => 'Serum'],
                ['name' => 'VDRL (Q&Q)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'TPHA (Qualitative)', 'price' => 350, 'specimen' => 'Serum'],
                ['name' => 'TPHA (Q&Q)', 'price' => 450, 'specimen' => 'Serum'],
            ],
            'IMMUNOCHROMATOGRAPHY (ICT)' => [
                ['name' => 'Dengue NS1 Antigen', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'Dengue Antibody (IgG & IgM)', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'Chikungunya Antibody (IgG & IgM)', 'price' => 500, 'specimen' => 'Serum'],
                ['name' => 'ICT for Malarial pv/pf', 'price' => 250, 'specimen' => 'Serum'],
                ['name' => 'ICT for Filaria', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'ICT for Salmonella/Typhoid', 'price' => 350, 'specimen' => 'Serum'],
                ['name' => 'ICT for Kala-azar/Leishmania Ab', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'ICT for Syphilis', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'H. Pylori Antibody (Qualitative)', 'price' => 400, 'specimen' => 'Serum'],
                ['name' => 'Stool for H. Pylori Antigen', 'price' => 650, 'specimen' => 'Stool'],
                ['name' => 'Anti TB Antibody (ICT )', 'price' => 450, 'specimen' => 'Serum'],
                ['name' => 'Urine for Pregnancy Test (ICT)', 'price' => 100, 'specimen' => 'Urine'],
            ],
            'VITAMINS' => [
                ['name' => 'Vitamin B-12', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => '25-OH Vitamin D (Total)', 'price' => 1000, 'specimen' => 'Serum'],
            ],
            'FLUID ANALYSIS/STUDY' => [
                ['name' => 'Fluid for Sugar/Glucose', 'price' => 200, 'specimen' => 'Fluid'],
                ['name' => 'Fluid for Protein', 'price' => 200, 'specimen' => 'Fluid'],
                ['name' => 'Fluid for Albumin', 'price' => 200, 'specimen' => 'Fluid'],
                ['name' => 'Fluid for ADA', 'price' => 600, 'specimen' => 'Fluid'],
                ['name' => 'Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Fluid'],
                ['name' => 'Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Fluid'],
                ['name' => 'Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Fluid'],
                ['name' => 'Fluid Study (Biochemistry,Microbiology,Cytology)', 'price' => 1500, 'specimen' => 'Fluid'],
                ['name' => 'Serum Ascites Albumin Gradient (SAAG)', 'price' => 600, 'specimen' => 'Fluid'],
                ['name' => 'Pleural Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pleural Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pleural Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pleural Fluid for ADA', 'price' => 600, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Pleural Fluid for LDH', 'price' => 400, 'specimen' => 'Pleural Fluid'],
                ['name' => 'Synovial Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Synovial Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Synovial Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Synovial Fluid for ADA', 'price' => 600, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Synovial Fluid for LDH', 'price' => 400, 'specimen' => 'Synovial Fluid'],
                ['name' => 'Ascitic Fluid for Biochemistry (Sugar,Protein)', 'price' => 500, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Ascitic Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Ascitic Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Ascitic Fluid for ADA', 'price' => 600, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Ascitic Fluid for LDH', 'price' => 400, 'specimen' => 'Ascitic Fluid'],
                ['name' => 'Aspirate Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Aspirate Fluid'],
                ['name' => 'Aspirate Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Aspirate Fluid'],
                ['name' => 'Aspirate Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Aspirate Fluid'],
                ['name' => 'Aspirate Fluid for ADA', 'price' => 600, 'specimen' => 'Aspirate Fluid'],
                ['name' => 'Pericardial Fluid for Biochemistry (Sugar,Protein,Album)', 'price' => 500, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Pericardial Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Pericardial Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Pericardial Fluid for ADA', 'price' => 600, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Pericardial Fluid for LDH', 'price' => 400, 'specimen' => 'Pericardial Fluid'],
                ['name' => 'Peritoneal Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Peritoneal Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Peritoneal Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Peritoneal Fluid for ADA', 'price' => 600, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Peritoneal Fluid for LDH', 'price' => 400, 'specimen' => 'Peritoneal Fluid'],
                ['name' => 'Cystic Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Cystic Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Cystic Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Cystic Fluid for ADA', 'price' => 600, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Cystic Fluid for LDH', 'price' => 400, 'specimen' => 'Cystic Fluid'],
                ['name' => 'Joint Fluid for Biochemistry (Sugar,Protein)', 'price' => 400, 'specimen' => 'Joint Fluid'],
                ['name' => 'Joint Fluid for Microbiology (AFB,Gram,CS)', 'price' => 600, 'specimen' => 'Joint Fluid'],
                ['name' => 'Joint Fluid for Cytology/Malignant Cell', 'price' => 500, 'specimen' => 'Joint Fluid'],
                ['name' => 'Joint Fluid for ADA', 'price' => 600, 'specimen' => 'Joint Fluid'],
                ['name' => 'Joint Fluid for LDH', 'price' => 400, 'specimen' => 'Joint Fluid'],
            ],
            'DRUG MONITORING' => [
                ['name' => 'Dope Test', 'price' => 1500, 'specimen' => 'Urine'],
                ['name' => 'Urine for Amphitamine', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Urine for Canabinoids', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Urine for Opiates', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Urine for Benzodiazepine', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Urine for Alcohol', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Urine for Cocaine', 'price' => 450, 'specimen' => 'Urine'],
                ['name' => 'Gentamicin', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Phenobarbital', 'price' => 1000, 'specimen' => 'Serum'],
                ['name' => 'Homocysteine', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'S. Alcohol/Ethanol', 'price' => 1500, 'specimen' => 'Serum'],
                ['name' => 'Valproic Acid', 'price' => 800, 'specimen' => 'Serum'],
                ['name' => 'Carbamazepine / Tegretol', 'price' => 1600, 'specimen' => 'Serum'],
            ],
            'MOLECULAR' => [
                ['name' => 'HBV DNA (PCR) (Quantitative)', 'price' => 3000, 'specimen' => 'EDTA'],
                ['name' => 'HCV RNA (PCR) (Quantitative)', 'price' => 4000, 'specimen' => 'EDTA'],
                ['name' => 'HLA-B27', 'price' => 1400, 'specimen' => 'EDTA'],
                ['name' => 'Karyotyping/Chromosome Analysis', 'price' => 5000, 'specimen' => 'Sodium Heparin'],
                ['name' => 'Human Papilloma Virus (HPV)-DNA', 'price' => 4000, 'specimen' => 'Cervical Swab'],
                ['name' => 'Gene Xpert', 'price' => 4000, 'specimen' => 'Required Sample'],
                ['name' => 'MTB-DNA (Mycobacterium Tuberculosis)', 'price' => 4000, 'specimen' => 'Required Sample'],
                ['name' => 'Dengue+Chikungunya+Zika (RT PCR)', 'price' => 3000, 'specimen' => 'EDTA'],
            ],
        ];

        $sortOrder = 1;
        foreach ($data as $subName => $services) {
            $subCategory = ServiceSubCategory::updateOrCreate(
                [
                    'service_category_id' => $category->id,
                    'slug' => Str::slug($subName)
                ],
                [
                    'name' => $subName,
                    'status' => true,
                    'sort_order' => $sortOrder++,
                ]
            );

            foreach ($services as $s) {
                Service::updateOrCreate(
                    ['name' => $s['name'], 'service_sub_category_id' => $subCategory->id],
                    [
                        'service_category_id' => $category->id,
                        'category' => $category->type,
                        'price' => $s['price'],
                        'specimen_type' => $s['specimen'] ?? null,
                        'status' => true,
                        'show_on_frontend' => true,
                        'home_visit_available' => true,
                    ]
                );
            }
        }
    }
}
